# Site settings
title: Form Function & Class 7
email: info@pwdo.org
date: October 22, 2016
description: Learn from the brightest minds in design and front-end at Form Function & Class, the pioneering web design conference in Asia.
baseurl: ""
# url: "http://2016.formfunctionclass.com" # Online
# url: "http://ss.formfunctionclass.com" # Online
url: "http://127.0.0.1:4000" # Local
# url: "http://192.168.1.107:4000" # Local Test
twitter_username: ffcph
github_username:  pwdo
exclude: ["node_modules", "bower_components", "Gruntfile.js", "package.json", "bower.json", "css/dev", "js/dev", "readme.md", "CNAME"]

# Build settings
markdown: kramdown